# 定时下载器时间配置文件
# 修改此文件后重启定时器程序即可生效

[scheduler]
# 定时执行时间配置
# 格式：["HH:MM", "HH:MM", ...]
# 使用24小时制，例如：
# - "08:30" 表示上午8点30分
# - "14:15" 表示下午2点15分
# - "23:45" 表示晚上11点45分

# 默认配置：凌晨2点、中午12点、晚上7点
times = ["02:00","06:00", "11:00", "15:00", "19:00", "21:00"]

# 其他预设配置示例（取消注释即可使用）：

# 工作时间配置（上班族适用）
# times = ["08:00", "12:30", "18:00", "22:00"]

# 学生时间配置
# times = ["07:30", "12:00", "17:30", "21:00"]

# 夜猫子配置
# times = ["10:00", "15:00", "20:00", "01:00"]

# 高频下载配置（每3小时一次）
# times = ["00:00", "03:00", "06:00", "09:00", "12:00", "15:00", "18:00", "21:00"]

# 每6小时配置
# times = ["00:00", "06:00", "12:00", "18:00"]

# 自定义配置说明：
# 1. 时间格式必须是 "HH:MM"，如 "09:30"
# 2. 小时使用24小时制，范围 00-23
# 3. 分钟范围 00-59
# 4. 可以添加任意多个时间点
# 5. 时间点之间用逗号分隔
# 6. 修改后需要重启定时器才能生效

[settings]
# 定时器相关设置
enabled = true  # 是否启用定时器
timezone = "Asia/Shanghai"  # 时区设置